# Generated by Django 6.0.5 on 2026-05-24 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('channel_type', models.CharField(choices=[('text', '# Text'), ('announcement', '📢 Announcement'), ('prayer', '🙏 Prayer'), ('study', '📖 Study')], default='text', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_read_only', models.BooleanField(default=False, help_text='Only admins/owner can post (e.g. announcements)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'channels',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='✝️', help_text='Emoji used as the community icon', max_length=10)),
                ('banner_color', models.CharField(default='#1e1b4b', help_text='Hex color for the community banner', max_length=7)),
                ('invite_code', models.CharField(blank=True, help_text='Short code others use to search and join', max_length=12, unique=True)),
                ('is_public', models.BooleanField(default=True)),
                ('member_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communities',
                'ordering': ['-member_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '👑 Owner'), ('admin', '🛡️ Admin'), ('member', '👤 Member')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(blank=True, default='', max_length=80)),
            ],
            options={
                'db_table': 'memberships',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'channel_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'message_reactions',
            },
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_post_id_015fcc_idx',
        ),
        migrations.RemoveIndex(
            model_name='discussionpost',
            name='discussion__author__fd9d9d_idx',
        ),
        migrations.RemoveIndex(
            model_name='discussionpost',
            name='discussion__created_3c6c3a_idx',
        ),
        migrations.AddField(
            model_name='community',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='community.community'),
        ),
        migrations.AddField(
            model_name='membership',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.community'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='community.channel'),
        ),
        migrations.AddField(
            model_name='message',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='community.message'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.message'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='discussionpost',
            name='author',
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['invite_code'], name='communities_invite__530408_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['name'], name='communities_name_788a30_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['community', 'position'], name='channels_communi_e89bdb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('community', 'name')},
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['community', 'user'], name='memberships_communi_25fa10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('community', 'user')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['channel', 'created_at'], name='channel_mes_channel_0d6d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['author'], name='channel_mes_author__2f5ad3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('message', 'user', 'emoji')},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='DiscussionPost',
        ),
    ]
