# Generated by Django 6.0.5 on 2026-05-21 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_days', models.PositiveIntegerField()),
                ('cover_image_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reading_plans',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Devotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('scripture_reference', models.CharField(help_text='e.g., "John 3:16-17"', max_length=100)),
                ('content', models.TextField(help_text='The devotional reflection text')),
                ('prayer', models.TextField(blank=True, default='', help_text='Closing prayer')),
                ('reflection_question', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devotionals', to='devotional.readingplan')),
            ],
            options={
                'db_table': 'devotionals',
                'ordering': ['plan', 'day_number'],
                'unique_together': {('plan', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='UserPlanProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='devotional.readingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_plan_progress',
                'indexes': [models.Index(fields=['user', 'plan'], name='user_plan_p_user_id_f84c2d_idx')],
                'unique_together': {('user', 'plan')},
            },
        ),
    ]
