# Generated by Django 6.0.5 on 2026-05-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotional',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='devotional',
            name='prayer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='devotional',
            name='scripture_reference',
            field=models.CharField(max_length=100),
        ),
    ]
