# Generated by Django 6.0.5 on 2026-05-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotional', '0002_alter_devotional_content_alter_devotional_prayer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingplan',
            options={'ordering': ['-is_featured', 'title']},
        ),
        migrations.AddField(
            model_name='readingplan',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in recommended plans on empty search'),
        ),
        migrations.AddField(
            model_name='readingplan',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated: prayer,faith,gospel,psalms,new testament', max_length=300),
        ),
    ]
