# Generated by Django 6.0.5 on 2026-05-21 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('book', models.CharField(blank=True, default='', max_length=50)),
                ('chapter', models.PositiveIntegerField(blank=True, null=True)),
                ('verse', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated tags: "faith, grace, love"', max_length=500)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_notes',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'book'], name='study_notes_user_id_df6ced_idx'), models.Index(fields=['user', 'is_favorite'], name='study_notes_user_id_39679b_idx')],
            },
        ),
    ]
